#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_REDEN_VERSION=${VERSION_STRING[2]}
ELECTRUM_REDEN_VERSION=${ELECTRUM_REDEN_VERSION#\'}
ELECTRUM_REDEN_VERSION=${ELECTRUM_REDEN_VERSION%\'}
DOTS=`echo $ELECTRUM_REDEN_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_REDEN_APK_VERSION=$ELECTRUM_REDEN_VERSION.0
else
    ELECTRUM_REDEN_APK_VERSION=$ELECTRUM_REDEN_VERSION
fi
export ELECTRUM_REDEN_VERSION
export ELECTRUM_REDEN_APK_VERSION
